### ISSUE TITLE
Repo still used?

### ISSUE THREAD

**Issue by maoo** [finos/ScreenSnippet#15]
Hi @VishwasShashidhar !

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by VishwasShashidhar** [comment]
Hello @maoo, I'm no longer managing anything related to Symphony. Maybe @KiranNiranjan / @keerthi16  can help you with this.

@KiranNiranjan / @keerthi16 If you are not involved in managing this anymore, please tag anyone you know.

**Comment by KiranNiranjan** [comment]
@sbenmoussati Can you please take a look? Thanks

**Comment by TheJuanAndOnly99** [comment]
Will proceed with project archival.

**Comment by finos-admin** [comment]
archiving project.
